<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="aviso">
    <xsd:complexType mixed="true">

      <xsd:sequence>

        <xsd:element name="nome" type="xsd:string"/>

        <xsd:element name="numerotrabalho"
                     type="xsd:positiveInteger"/>

        <xsd:element name="dataentrega"
                     type="xsd:date"
                     minOccurs="0"
                     maxOccurs="2"/>

        <xsd:choice minOccurs="1" maxOccurs="2">
          <xsd:element name="email" type="xsd:string"/>
          <xsd:element name="telefone" type="xsd:string"/>
        </xsd:choice>

      </xsd:sequence>

    </xsd:complexType>
  </xsd:element>

</xsd:schema>